### ISSUE TITLE
Change the design of dropdown

### ISSUE THREAD

**Issue by shreyans29** [systers/FirstAide-web#174] opened 2017-03-11 10:19 UTC
The css for the new drop down which has been added can be changed to the design of the dropdown  as in the below screenshot.

![screenshot 993](https://cloud.githubusercontent.com/assets/8592568/23822370/e48ad56e-0671-11e7-8b3b-ad83de3b7e36.png)

![screenshot 992](https://cloud.githubusercontent.com/assets/8592568/23822369/e4872b94-0671-11e7-8aef-c58909493c34.png)

**Comment by AkankshaBodhankar** [comment] 2017-03-13 04:58
Yes you can go ahead with this.

**Comment by sayedafif** [comment] 2017-03-22 18:03
@AkankshaBodhankar The select box is having default styling. Hence it shows up differently in different browsers. We can either put an image icon for the arrow instead of the default arrow or we need to write CSS. Can I work on this?

**Comment by AkankshaBodhankar** [comment] 2017-03-23 04:58
@sayedafif Generally the person who creates the issue is assigned to it. You can go through the rules of contributing in the readme file. The issue you are mentioning will be resolved when the PR for this will be made. You can find more bugs in the project and create a new issue for it.

**Comment by fatimarafiqui** [comment] 2017-06-14 06:17
@AkankshaBodhankar @MehaKaushik @prathmeshranaut @npari This is also covered in Login/Signup Responsiveness.

**Closed** 2017-06-14 06:19 UTC
Labels: enhancement, open
